[package]
name = "Streams"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


anyhow = { version = "1.0", default-features = false }
iota-streams = { version = "0.1.2", path = "../streams" }
